=== alexfviana/Painel_de_Vendas/ETL/TabSabor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="TabSabor" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="TabSabor">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Código da Família" index-key="Código_x0020_da_x0020_Família " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Código do Sabor" index-key="Código_x0020_do_x0020_Sabor " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="nCknCp/SyEGAT4eg5C3DHw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACcKScKn9LIQYBPh6DkLcMfAAAAAPZn8fXrf+VAAAAAAAAAAABTAGEA
YgBvAHIAZQBzAAAAAAAAAFRsXABHPi5GuAoEZfpq7poHAAAAnCknCp/SyEGAT4eg
5C3DH0MA8wBkAGkAZwBvACAAZABvACAAUwBhAGIAbwByAAAAAAAAAGQxelXR2ddB
lkmpG/b5o3YHAAAAnCknCp/SyEGAT4eg5C3DH04AbwBtAGUAIABkAG8AIABTAGEA
YgBvAHIAAAAAAAAAIB9kpMTBMkyAOoG6Cy+lXQcAAACcKScKn9LIQYBPh6DkLcMf
QwDzAGQAaQBnAG8AIABkAGEAIABGAGEAbQDtAGwAaQBhAAAAAAAAAI6R4GYGUWxE
gaqqCeKWiL4HAAAAnCknCp/SyEGAT4eg5C3DH1YAYQBsAG8AcgAgAFIAZQBmAGUA
cgDqAG4AYwBpAGEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAA
AAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Código_x0020_do_x0020_Sabor" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="VGxcAEc+Lka4CgRl+mrumg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Nome_x0020_do_x0020_Sabor" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="ZDF6VdHZ10GWSakb9vmjdg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Código_x0020_da_x0020_Família" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="IB9kpMTBMkyAOoG6Cy+lXQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Valor_x0020_Referência" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="Standard"/>
<od:fieldProperty name="GUID" type="9" value="jpHgZgZRbESBqqoJ4paIvg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== alexfviana/Painel_de_Vendas/ETL/TabSabor.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="TabSabor.xsd" generated="2020-07-19T09:05:14">
<TabSabor>
<Código_x0020_do_x0020_Sabor>0001-7</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Abacate</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>124.94</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0002-6</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Abacaxi</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>129.02</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0003-5</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Abacaxi com Hortelã</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>44.46</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0004-4</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Abóbora com Coco</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>114.67</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0005-3</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Acerola</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>68.74</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0006-2</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Ameixa</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>46.38</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0007-1</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Amora</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>99.77</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0008-0</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Araçá</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>47.23</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0009-8</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Atemóia</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>47.92</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0010-7</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Bacuri</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>42.91</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0011-6</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Blueberry</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>42.29</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0012-5</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Cajá</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>74.44</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0013-4</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Caju</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>63.08</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0014-3</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Caqui</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>120.82</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0015-2</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Carambola</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>87.32</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0016-1</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Castanha-do-pará</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>52.41</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0017-0</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Cerveja</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>117.47</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0018-8</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Cupuaçu</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>109.22</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0019-7</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Damasco</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>49.43</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0020-6</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Damasco com Tomilho</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>69.11</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0021-5</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Figo com Água de Coco</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>71.46</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0022-4</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Framboesa</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>56.97</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0023-3</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Framboesa com Limão Siciliano</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>69.47</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0024-2</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Fruta-do-conde</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>93</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0025-1</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Frutas Secas</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>66.16</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0026-0</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Frutas Vermelhas</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>110.09</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0027-8</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Goiaba</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>82.8</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0028-7</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Graviola</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>121.9</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0029-6</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Jabuticaba</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>44.86</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0030-5</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Jaca</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>64.11</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0031-4</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Laranja</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>78.69</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0032-3</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Laranja com Beterraba e Cenoura</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>72.25</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0033-2</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Laranja-limão</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>70.48</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0034-1</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Lichia</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>86.45</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0035-0</Código_x0020_do_x0020_Sabor>
<Nome_x0020_do_x0020_Sabor>Limão</Nome_x0020_do_x0020_Sabor>
<Código_x0020_da_x0020_Família>F</Código_x0020_da_x0020_Família>
<Valor_x0020_Referência>82.41</Valor_x0020_Referência>
</TabSabor>
<TabSabor>
<Código_x0020_do_x0020_Sabor>0036-8</Código_x0020_do_x0020_Sabor>
